//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inzynierka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniOrder
    {
        public int ID { get; set; }
        public int SuperOrder_ID { get; set; }
        public int Product_ID { get; set; }
        public int Amount { get; set; }
        public decimal Total { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual SuperOrder SuperOrder { get; set; }
    }
}
