//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inzynierka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int Products_ID { get; set; }
        public System.DateTime Order_date { get; set; }
        public int Amount { get; set; }
        public string Client_FirstName { get; set; }
        public string Client_LastName { get; set; }
        public string Client_Address { get; set; }
        public string Zip_Code { get; set; }
        public string City { get; set; }
        public string Client_Tel { get; set; }
        public string Client_Email { get; set; }
        public decimal Total { get; set; }
    }
}
